repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        files: r'*.py'
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: double-quote-string-fixer
    -   id: no-commit-to-branch
        args: ['--pattern', '^(?!((feature|bugfix|release|hotfix)\/\w+)$)']
-   repo: https://github.com/PyCQA/isort.git
    rev: 5.6.4
    hooks:
    -   id: isort